### ISSUE TITLE
AUR package available

### ISSUE THREAD

**Issue by sanderboom** [n4n0GH/breezeway-mod#11]
I was about to create an AUR package, but someone got first: https://aur.archlinux.org/packages/breezeway-mod-git/

You could add  something like: `yay -S breezeway-mod-git` to `README.md` to toot the horn about it.

**Comment by n4n0GH** [comment]
Oh that's pretty dope! Someone on Reddit provided me with a PKGBUILD but I haven't gotten around to get this done. Will this resolve the build dependencies when installing with your command?

**Comment by n4n0GH** [comment]
Apparently it does. Added to the ```README.md```, thanks for pointing that out!
