### ISSUE TITLE
Weird behaviour after blocking compositing.

### ISSUE THREAD

**Issue by vllur** [n4n0GH/breezeway-mod#14]
Window decorations are getting random flickering visual glitches after closing an app that was blocking compositing.

As far as I checked, there's nothing interesting in journald logs. Only entries related to compositioning are "Painter not active" and "Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated" stuff.

I'm using Manjaro, intel graphics and breezeway-mod from AUR. Auto color match is
 set to "Color scheme". That's how it looks (here it mirrored part of bottom of the screen):
![bug](https://user-images.githubusercontent.com/24637251/68618151-078f7080-04c9-11ea-8160-6273b34add3d.png)

**Comment by n4n0GH** [comment]
How could I reproduce this? I tried forcing a "compositing: block" behaviour on a random window, moving it on top of another and then closing it but I wasn't able to see these glitches.

**Comment by Schlaefer** [comment]
Manjaro, Intel HD 620, X here. Same issue: after a the compositor was disabled and enabled again wild flickering starts. But it only happens on the OpenGL 3.1 engine, OpenGL 2.0 and XRender is OK.

**Comment by n4n0GH** [comment]
I'll try to recreate this behavior again tonight.

12. Nov. 2019, 15:52 von notifications@github.com:

**Comment by vllur** [comment]
Apparently after messing around today I can't force it to happen again. Changing the rendering backend or the color matching method also don't work (or rather, work, besides the beta window color matching which is totally broken on my setup). 
So, idk, maybe for me it was caused by some weird circumstances?

**Comment by n4n0GH** [comment]
I'm really trying my best to get this glitch to appear on my screen but to no avail. Sorry. I'm closing the issue for now but feel free to comment if you found a way to recreate a scenario where we can force the glitch to appear.
