### ISSUE TITLE
Publish on KDE store

### ISSUE THREAD

**Issue by cemetary** [n4n0GH/breezeway-mod#2]
What the title indicates.

**Comment by n4n0GH** [comment]
How the hell does one publish anything there? I registered but I have no clue wtf is going on lmao. Will look into it later.

**Comment by n4n0GH** [comment]
That site is a clusterfuck of menus. Anyway, here's the thing on KDE Store https://store.kde.org/p/1332155/

**Comment by cemetary** [comment]
Thanks...

Just one more thing. I think you published it in the wrong category, this theme should be in "[Aurorae Theme](https://i.imgur.com/8hnJLPZ.png)" instead of "Plasma Theme", otherwise it won't show up on KDE Plasma [System Settings](https://i.imgur.com/SbWCagh.png).

Sorry about that. 😅

**Comment by n4n0GH** [comment]
But it's not an Aurorae Theme :thinking: 
I'll just republish or whatever no worries.
