### ISSUE TITLE
Readme is in need of an update

### ISSUE THREAD

**Issue by n4n0GH** [n4n0GH/breezeway-mod#6]
Installation instructions on the readme file are not good enough. Needs a detailed update.

**Comment by n4n0GH** [comment]
To clarify: the update that is needed is detailed instructions on how to install the dependencies on a per-platform base.

**Comment by tim-hilt** [comment]
I built it from source and had to install a few dependencies on the way. In the end everything was working seamlessly.
I tested this process on KDE Neon for now. Would a list of these dependencies help? I'm not (yet) a pkgbuilder and have not created build/install-instructions yet but want to contribute and help this project. Learning a few things on the way wouldn't hurt.
I run Arch on my main machine if this information is helpful.

**Comment by n4n0GH** [comment]
Oh yeah, sure. If you could provide a list in combination with your OS that'd be dope. Just paste it in here :+1:

**Comment by tim-hilt** [comment]
Read too late! I created a PR, but feel free to reject if that‘s not what you had in mind!

**Comment by n4n0GH** [comment]
That works, too. Good job!

**Comment by tim-hilt** [comment]
Thanks! This was my first ever PR to be honest!
Can you name a few distros that you would like to have in the description? I would go see what i can do.

**Comment by n4n0GH** [comment]
I guess Arch as a base would cover a lot of distributions, openSUSE I can do myself, missing Fedora. It's probably the same on all of those, just how to obtain the packages is what interests me: does the user need to scuttle through old forum posts from 2009 to find an obscure ZIP or is it available in the repositories?

**Comment by n4n0GH** [comment]
@tim-hilt Might also wanna take a look at https://github.com/nana-4/materia-theme to get an example of what (I think) is a pretty detailed Readme.

**Comment by n4n0GH** [comment]
Okay I think b780d25 rounded off the entire readme pretty well. Thanks to everyone for helping me on this!
